name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t arish120/next-js-app:latest
      - run: echo "dckr_pat_qGJwdQaB2vYzcEj0K3jyf8GrLk4" | docker login -u arish120 --password-stdin
      - run: docker push arish120/next-js-app:latest
